// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zqautesftzbjnqrjfemy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpxYXV0ZXNmdHpiam5xcmpmZW15Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE5ODY5MDYsImV4cCI6MjA2NzU2MjkwNn0.FVekkRRfy_9s6_rlmR0TsEUJ1I4Z7NhCCIODS4NM_wM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});